// Auto-generated from CMU Pronouncing Dictionary filtered to ENABLE word list.
// 1309 homophone groups — all entries are valid game words.
// Each key maps to its homophones (bidirectional).
export const HOMOPHONES: Record<string, string[]> = {
  abbe: ['abbey'],
  abbey: ['abbe'],
  acclamation: ['acclimation'],
  acclimation: ['acclamation'],
  accouterment: ['accoutrement'],
  accoutrement: ['accouterment'],
  accouterments: ['accoutrements'],
  accoutrements: ['accouterments'],
  acetic: ['ascetic'],
  ascetic: ['acetic'],
  acknowledgement: ['acknowledgment'],
  acknowledgment: ['acknowledgement'],
  adapter: ['adaptor'],
  adaptor: ['adapter'],
  adapters: ['adaptors'],
  adaptors: ['adapters'],
  addition: ['edition'],
  edition: ['addition'],
  adman: ['admen'],
  admen: ['adman'],
  adviser: ['advisor'],
  advisor: ['adviser'],
  advisers: ['advisors'],
  advisors: ['advisers'],
  aerial: ['ariel'],
  ariel: ['aerial'],
  aerie: ['airy', 'eyrie'],
  airy: ['aerie', 'eyrie'],
  eyrie: ['aerie', 'airy'],
  aero: ['arrow'],
  arrow: ['aero'],
  aesthetic: ['esthetic'],
  esthetic: ['aesthetic'],
  aesthetics: ['esthetics'],
  esthetics: ['aesthetics'],
  affect: ['effect'],
  effect: ['affect'],
  aides: ['aids'],
  aids: ['aides'],
  ails: ['ales'],
  ales: ['ails'],
  aired: ['erred'],
  erred: ['aired'],
  airing: ['erring'],
  erring: ['airing'],
  airs: ['errs', 'heirs'],
  errs: ['airs', 'heirs'],
  heirs: ['airs', 'errs'],
  aisle: ['isle'],
  isle: ['aisle'],
  aisles: ['isles'],
  isles: ['aisles'],
  alfa: ['alpha'],
  alpha: ['alfa'],
  align: ['aline'],
  aline: ['align'],
  aligns: ['alines'],
  alines: ['aligns'],
  allowed: ['aloud'],
  aloud: ['allowed'],
  altar: ['alter'],
  alter: ['altar'],
  altars: ['alters'],
  alters: ['altars'],
  ambiance: ['ambience'],
  ambience: ['ambiance'],
  amok: ['amuck'],
  amuck: ['amok'],
  analog: ['analogue'],
  analogue: ['analog'],
  anas: ['anise'],
  anise: ['anas'],
  annal: ['annul'],
  annul: ['annal'],
  ante: ['anti', 'auntie'],
  anti: ['ante', 'auntie'],
  auntie: ['ante', 'anti'],
  ants: ['aunts'],
  aunts: ['ants'],
  apatite: ['appetite'],
  appetite: ['apatite'],
  apatites: ['appetites'],
  appetites: ['apatites'],
  appel: ['apple'],
  apple: ['appel'],
  apprise: ['uprise'],
  uprise: ['apprise'],
  arbitrager: ['arbitrageur'],
  arbitrageur: ['arbitrager'],
  arbor: ['arbour'],
  arbour: ['arbor'],
  archaeological: ['archeological'],
  archeological: ['archaeological'],
  archaeology: ['archeology'],
  archeology: ['archaeology'],
  ares: ['hours', 'ours'],
  hours: ['ares', 'ours'],
  ours: ['ares', 'hours'],
  argyle: ['argyll'],
  argyll: ['argyle'],
  armer: ['armor', 'armour'],
  armor: ['armer', 'armour'],
  armour: ['armer', 'armor'],
  ascendancy: ['ascendency'],
  ascendency: ['ascendancy'],
  ascent: ['assent'],
  assent: ['ascent'],
  ates: ['eights'],
  eights: ['ates'],
  auger: ['augur'],
  augur: ['auger'],
  augers: ['augurs'],
  augurs: ['augers'],
  aural: ['oral'],
  oral: ['aural'],
  axel: ['axle'],
  axle: ['axel'],
  ayes: ['eyes'],
  eyes: ['ayes'],
  babble: ['babel'],
  babel: ['babble'],
  bach: ['bock'],
  bock: ['bach'],
  bade: ['bayed'],
  bayed: ['bade'],
  baggie: ['baggy'],
  baggy: ['baggie'],
  baht: ['bott', 'bought'],
  bott: ['baht', 'bought'],
  bought: ['baht', 'bott'],
  bail: ['bale'],
  bale: ['bail'],
  bailer: ['bailor', 'baler'],
  bailor: ['bailer', 'baler'],
  baler: ['bailer', 'bailor'],
  bailey: ['bailie', 'bally'],
  bailie: ['bailey', 'bally'],
  bally: ['bailey', 'bailie'],
  bailing: ['baling'],
  baling: ['bailing'],
  bails: ['bales'],
  bales: ['bails'],
  bait: ['bate'],
  bate: ['bait'],
  baited: ['bated'],
  bated: ['baited'],
  baits: ['bates'],
  bates: ['baits'],
  baize: ['bays'],
  bays: ['baize'],
  balas: ['ballasts'],
  ballasts: ['balas'],
  bald: ['balled', 'bawled'],
  balled: ['bald', 'bawled'],
  bawled: ['bald', 'balled'],
  ball: ['bawl'],
  bawl: ['ball'],
  balm: ['bomb'],
  bomb: ['balm'],
  balms: ['bombs'],
  bombs: ['balms'],
  baloney: ['bologna'],
  bologna: ['baloney'],
  band: ['banned'],
  banned: ['band'],
  banister: ['bannister'],
  bannister: ['banister'],
  barb: ['barbe'],
  barbe: ['barb'],
  barbecue: ['barbeque'],
  barbeque: ['barbecue'],
  barbecued: ['barbequed'],
  barbequed: ['barbecued'],
  barbecues: ['barbeques'],
  barbeques: ['barbecues'],
  bard: ['barred'],
  barred: ['bard'],
  bare: ['bear'],
  bear: ['bare'],
  bares: ['bears'],
  bears: ['bares'],
  baring: ['bearing'],
  bearing: ['baring'],
  baron: ['barren'],
  barren: ['baron'],
  barons: ['barrens'],
  barrens: ['barons'],
  barre: ['berry', 'bury'],
  berry: ['barre', 'bury'],
  bury: ['barre', 'berry'],
  barrel: ['beryl'],
  beryl: ['barrel'],
  barres: ['bars'],
  bars: ['barres'],
  base: ['bass'],
  bass: ['base'],
  based: ['baste'],
  baste: ['based'],
  bases: ['basses'],
  basses: ['bases'],
  bask: ['basque'],
  basque: ['bask'],
  basks: ['basques'],
  basques: ['basks'],
  basset: ['bassett'],
  bassett: ['basset'],
  baton: ['batten'],
  batten: ['baton'],
  bats: ['batts'],
  batts: ['bats'],
  bauble: ['bobble'],
  bobble: ['bauble'],
  baubles: ['bobbles'],
  bobbles: ['baubles'],
  baud: ['bawd'],
  bawd: ['baud'],
  bazaar: ['bazar', 'bizarre'],
  bazar: ['bazaar', 'bizarre'],
  bizarre: ['bazaar', 'bazar'],
  beach: ['beech'],
  beech: ['beach'],
  beachy: ['beechy'],
  beechy: ['beachy'],
  beat: ['beet'],
  beet: ['beat'],
  beats: ['beets'],
  beets: ['beats'],
  beau: ['beaux'],
  beaux: ['beau'],
  been: ['bunn'],
  bunn: ['been'],
  begins: ['biggins'],
  biggins: ['begins'],
  bell: ['belle'],
  belle: ['bell'],
  belles: ['bells', 'bels'],
  bells: ['belles', 'bels'],
  bels: ['belles', 'bells'],
  below: ['billow'],
  billow: ['below'],
  benefited: ['benefitted'],
  benefitted: ['benefited'],
  benefiting: ['benefitting'],
  benefitting: ['benefiting'],
  benzene: ['benzine'],
  benzine: ['benzene'],
  berg: ['burg'],
  burg: ['berg'],
  berries: ['buries'],
  buries: ['berries'],
  berth: ['birth'],
  birth: ['berth'],
  berths: ['births'],
  births: ['berths'],
  better: ['bettor'],
  bettor: ['better'],
  betters: ['bettors'],
  bettors: ['betters'],
  bibbs: ['bibs'],
  bibs: ['bibbs'],
  bight: ['bite', 'byte'],
  bite: ['bight', 'byte'],
  byte: ['bight', 'bite'],
  billed: ['build'],
  build: ['billed'],
  billie: ['billy'],
  billy: ['billie'],
  bird: ['burd'],
  burd: ['bird'],
  birk: ['burke'],
  burke: ['birk'],
  birks: ['burkes'],
  burkes: ['birks'],
  birle: ['burl'],
  burl: ['birle'],
  birr: ['burr'],
  burr: ['birr'],
  bise: ['buys'],
  buys: ['bise'],
  bites: ['bytes'],
  bytes: ['bites'],
  blase: ['blaze'],
  blaze: ['blase'],
  blessed: ['blest'],
  blest: ['blessed'],
  blew: ['blue'],
  blue: ['blew'],
  bloc: ['block'],
  block: ['bloc'],
  blocks: ['blocs'],
  blocs: ['blocks'],
  blond: ['blonde'],
  blonde: ['blond'],
  blondes: ['blonds'],
  blonds: ['blondes'],
  bloom: ['blume'],
  blume: ['bloom'],
  blueing: ['bluing'],
  bluing: ['blueing'],
  blueish: ['bluish'],
  bluish: ['blueish'],
  boar: ['bore'],
  bore: ['boar'],
  board: ['bored'],
  bored: ['board'],
  boarder: ['border'],
  border: ['boarder'],
  boarders: ['borders'],
  borders: ['boarders'],
  boart: ['bort'],
  bort: ['boart'],
  boasts: ['bowse'],
  bowse: ['boasts'],
  boche: ['botch'],
  botch: ['boche'],
  bode: ['bowed'],
  bowed: ['bode'],
  bogie: ['boogie'],
  boogie: ['bogie'],
  bolar: ['bowler'],
  bowler: ['bolar'],
  bold: ['bowled'],
  bowled: ['bold'],
  bolder: ['boulder'],
  boulder: ['bolder'],
  bole: ['boll', 'bowl'],
  boll: ['bole', 'bowl'],
  bowl: ['bole', 'boll'],
  boles: ['bolls', 'bowls'],
  bolls: ['boles', 'bowls'],
  bowls: ['boles', 'bolls'],
  bolling: ['bowling'],
  bowling: ['bolling'],
  boney: ['bony'],
  bony: ['boney'],
  bonnie: ['bonny'],
  bonny: ['bonnie'],
  boos: ['booze'],
  booze: ['boos'],
  bootie: ['booty'],
  booty: ['bootie'],
  born: ['borne', 'bourn', 'bourne'],
  borne: ['born', 'bourn', 'bourne'],
  bourn: ['born', 'borne', 'bourne'],
  bourne: ['born', 'borne', 'bourn'],
  borough: ['burro', 'burrow'],
  burro: ['borough', 'burrow'],
  burrow: ['borough', 'burro'],
  boroughs: ['burros', 'burrows'],
  burros: ['boroughs', 'burrows'],
  burrows: ['boroughs', 'burros'],
  boughs: ['bows'],
  bows: ['boughs'],
  bowman: ['bowmen'],
  bowmen: ['bowman'],
  brae: ['bray'],
  bray: ['brae'],
  brake: ['break'],
  break: ['brake'],
  brakes: ['breaks'],
  breaks: ['brakes'],
  braking: ['breaking'],
  breaking: ['braking'],
  bras: ['brass'],
  brass: ['bras'],
  breach: ['breech'],
  breech: ['breach'],
  breaching: ['breeching'],
  breeching: ['breaching'],
  bread: ['bred'],
  bred: ['bread'],
  brede: ['breed'],
  breed: ['brede'],
  bree: ['brie'],
  brie: ['bree'],
  brees: ['breeze'],
  breeze: ['brees'],
  brewed: ['brood'],
  brood: ['brewed'],
  brews: ['bruise'],
  bruise: ['brews'],
  briar: ['brier'],
  brier: ['briar'],
  bridal: ['bridle'],
  bridle: ['bridal'],
  brit: ['britt'],
  britt: ['brit'],
  brits: ['britts'],
  britts: ['brits'],
  broach: ['brooch'],
  brooch: ['broach'],
  brows: ['browse'],
  browse: ['brows'],
  brunet: ['brunette'],
  brunette: ['brunet'],
  brut: ['brute'],
  brute: ['brut'],
  burger: ['burgher'],
  burgher: ['burger'],
  burley: ['burly'],
  burly: ['burley'],
  bused: ['bussed', 'bust'],
  bussed: ['bused', 'bust'],
  bust: ['bused', 'bussed'],
  busing: ['bussing'],
  bussing: ['busing'],
  bute: ['butte'],
  butte: ['bute'],
  buts: ['butts'],
  butts: ['buts'],
  cabbie: ['cabby'],
  cabby: ['cabbie'],
  cache: ['cachet', 'cash'],
  cachet: ['cache', 'cash'],
  cash: ['cache', 'cachet'],
  cached: ['cashed'],
  cashed: ['cached'],
  caches: ['cashes'],
  cashes: ['caches'],
  caching: ['cashing'],
  cashing: ['caching'],
  cain: ['cane', 'kain', 'kane'],
  cane: ['cain', 'kain', 'kane'],
  kain: ['cain', 'cane', 'kane'],
  kane: ['cain', 'cane', 'kain'],
  calix: ['calyx'],
  calyx: ['calix'],
  calk: ['caulk', 'cock'],
  caulk: ['calk', 'cock'],
  cock: ['calk', 'caulk'],
  call: ['caul'],
  caul: ['call'],
  caller: ['color', 'culler'],
  color: ['caller', 'culler'],
  culler: ['caller', 'color'],
  callous: ['callus'],
  callus: ['callous'],
  campi: ['campy'],
  campy: ['campi'],
  campsite: ['campsites'],
  campsites: ['campsite'],
  canceled: ['cancelled'],
  cancelled: ['canceled'],
  canceling: ['cancelling'],
  cancelling: ['canceling'],
  canister: ['cannister'],
  cannister: ['canister'],
  canisters: ['cannisters'],
  cannisters: ['canisters'],
  cannon: ['canon'],
  canon: ['cannon'],
  cannons: ['canons'],
  canons: ['cannons'],
  canter: ['cantor'],
  cantor: ['canter'],
  canvas: ['canvass'],
  canvass: ['canvas'],
  canvases: ['canvasses'],
  canvasses: ['canvases'],
  capital: ['capitol'],
  capitol: ['capital'],
  capitals: ['capitols'],
  capitols: ['capitals'],
  capped: ['kept'],
  kept: ['capped'],
  carat: ['carrot', 'karat'],
  carrot: ['carat', 'karat'],
  karat: ['carat', 'carrot'],
  carats: ['carrots'],
  carrots: ['carats'],
  cargoes: ['cargos'],
  cargos: ['cargoes'],
  carles: ['carls'],
  carls: ['carles'],
  carman: ['carmen', 'carmine'],
  carmen: ['carman', 'carmine'],
  carmine: ['carman', 'carmen'],
  carn: ['karn'],
  karn: ['carn'],
  carns: ['karns'],
  karns: ['carns'],
  carol: ['carrel'],
  carrel: ['carol'],
  carousel: ['carrousel'],
  carrousel: ['carousel'],
  carry: ['kerry'],
  kerry: ['carry'],
  cars: ['cause', 'kaas'],
  cause: ['cars', 'kaas'],
  kaas: ['cars', 'cause'],
  cart: ['carte'],
  carte: ['cart'],
  casino: ['cassino'],
  cassino: ['casino'],
  cast: ['caste'],
  caste: ['cast'],
  caster: ['castor'],
  castor: ['caster'],
  castes: ['casts'],
  casts: ['castes'],
  catalog: ['catalogue'],
  catalogue: ['catalog'],
  cataloged: ['catalogued'],
  catalogued: ['cataloged'],
  catalogs: ['catalogues'],
  catalogues: ['catalogs'],
  cataract: ['cataracts'],
  cataracts: ['cataract'],
  cats: ['kats'],
  kats: ['cats'],
  catsup: ['ketchup'],
  ketchup: ['catsup'],
  caucus: ['coccus'],
  coccus: ['caucus'],
  caudal: ['caudle', 'coddle'],
  caudle: ['caudal', 'coddle'],
  coddle: ['caudal', 'caudle'],
  caught: ['khat'],
  khat: ['caught'],
  cease: ['seis'],
  seis: ['cease'],
  cedar: ['ceder'],
  ceder: ['cedar'],
  cede: ['seed'],
  seed: ['cede'],
  ceded: ['seeded'],
  seeded: ['ceded'],
  cedes: ['seeds'],
  seeds: ['cedes'],
  ceding: ['seeding'],
  seeding: ['ceding'],
  cees: ['seas', 'sees', 'seize'],
  seas: ['cees', 'sees', 'seize'],
  sees: ['cees', 'seas', 'seize'],
  seize: ['cees', 'seas', 'sees'],
  ceiling: ['sealing', 'seeling'],
  sealing: ['ceiling', 'seeling'],
  seeling: ['ceiling', 'sealing'],
  cell: ['sell', 'selle'],
  sell: ['cell', 'selle'],
  selle: ['cell', 'sell'],
  cellar: ['seller'],
  seller: ['cellar'],
  cellars: ['sellers'],
  sellers: ['cellars'],
  cells: ['cels', 'sells'],
  cels: ['cells', 'sells'],
  sells: ['cells', 'cels'],
  censer: ['censor', 'sensor'],
  censor: ['censer', 'sensor'],
  sensor: ['censer', 'censor'],
  censors: ['sensors'],
  sensors: ['censors'],
  cent: ['scent', 'sent'],
  scent: ['cent', 'sent'],
  sent: ['cent', 'scent'],
  center: ['centre'],
  centre: ['center'],
  centers: ['centres'],
  centres: ['centers'],
  cents: ['scents', 'sense'],
  scents: ['cents', 'sense'],
  sense: ['cents', 'scents'],
  cereal: ['serial'],
  serial: ['cereal'],
  cereals: ['serials'],
  serials: ['cereals'],
  ceres: ['series'],
  series: ['ceres'],
  chaise: ['shays'],
  shays: ['chaise'],
  chalk: ['chock'],
  chock: ['chalk'],
  chao: ['chow', 'ciao'],
  chow: ['chao', 'ciao'],
  ciao: ['chao', 'chow'],
  chard: ['charred'],
  charred: ['chard'],
  charley: ['charlie'],
  charlie: ['charley'],
  chased: ['chaste'],
  chaste: ['chased'],
  chews: ['choose', 'tews'],
  choose: ['chews', 'tews'],
  tews: ['chews', 'choose'],
  chic: ['sheik', 'sheikh'],
  sheik: ['chic', 'sheikh'],
  sheikh: ['chic', 'sheik'],
  childe: ['chilled'],
  chilled: ['childe'],
  chile: ['chili', 'chilly'],
  chili: ['chile', 'chilly'],
  chilly: ['chile', 'chili'],
  chiles: ['chilies', 'chillies'],
  chilies: ['chiles', 'chillies'],
  chillies: ['chiles', 'chilies'],
  choral: ['coral'],
  coral: ['choral'],
  chorale: ['corral'],
  corral: ['chorale'],
  chorals: ['corals'],
  corals: ['chorals'],
  chord: ['cord'],
  cord: ['chord'],
  chords: ['cords'],
  cords: ['chords'],
  christie: ['christy'],
  christy: ['christie'],
  churchman: ['churchmen'],
  churchmen: ['churchman'],
  chute: ['shoot', 'shute'],
  shoot: ['chute', 'shute'],
  shute: ['chute', 'shoot'],
  chutes: ['shoots', 'shutes'],
  shoots: ['chutes', 'shutes'],
  shutes: ['chutes', 'shoots'],
  cinch: ['synch'],
  synch: ['cinch'],
  cinque: ['sink', 'sync'],
  sink: ['cinque', 'sync'],
  sync: ['cinque', 'sink'],
  cipher: ['cypher'],
  cypher: ['cipher'],
  cist: ['cyst'],
  cyst: ['cist'],
  cite: ['sight', 'site'],
  sight: ['cite', 'site'],
  site: ['cite', 'sight'],
  cited: ['sighted', 'sited'],
  sighted: ['cited', 'sited'],
  sited: ['cited', 'sighted'],
  cites: ['sights', 'sites'],
  sights: ['cites', 'sites'],
  sites: ['cites', 'sights'],
  citing: ['sighting', 'siting'],
  sighting: ['citing', 'siting'],
  siting: ['citing', 'sighting'],
  clause: ['claws'],
  claws: ['clause'],
  cleek: ['clique'],
  clique: ['cleek'],
  clews: ['clues'],
  clues: ['clews'],
  clicks: ['cliques'],
  cliques: ['clicks'],
  climbs: ['climes'],
  climes: ['climbs'],
  close: ['clothes'],
  clothes: ['close'],
  coal: ['cole', 'kohl'],
  cole: ['coal', 'kohl'],
  kohl: ['coal', 'cole'],
  coals: ['coles', 'kohls'],
  coles: ['coals', 'kohls'],
  kohls: ['coals', 'coles'],
  coarse: ['corse', 'course'],
  corse: ['coarse', 'course'],
  course: ['coarse', 'corse'],
  coarser: ['courser'],
  courser: ['coarser'],
  coat: ['cote'],
  cote: ['coat'],
  coats: ['cotes'],
  cotes: ['coats'],
  coax: ['cokes'],
  cokes: ['coax'],
  cobbs: ['cobs', 'kobs'],
  cobs: ['cobbs', 'kobs'],
  kobs: ['cobbs', 'cobs'],
  cocky: ['khaki'],
  khaki: ['cocky'],
  coco: ['cocoa'],
  cocoa: ['coco'],
  code: ['coed'],
  coed: ['code'],
  coffing: ['coughing'],
  coughing: ['coffing'],
  coliseum: ['colosseum'],
  colosseum: ['coliseum'],
  collard: ['collared'],
  collared: ['collard'],
  collie: ['colly'],
  colly: ['collie'],
  colonel: ['kernel'],
  kernel: ['colonel'],
  colonels: ['kernels'],
  kernels: ['colonels'],
  colored: ['coloured'],
  coloured: ['colored'],
  colors: ['cullers'],
  cullers: ['colors'],
  colter: ['coulter'],
  coulter: ['colter'],
  comb: ['combe'],
  combe: ['comb'],
  combating: ['combatting'],
  combatting: ['combating'],
  combes: ['combs'],
  combs: ['combes'],
  complacent: ['complaisant'],
  complaisant: ['complacent'],
  complemented: ['complimented'],
  complimented: ['complemented'],
  complementing: ['complimenting'],
  complimenting: ['complementing'],
  comptroller: ['controller'],
  controller: ['comptroller'],
  conch: ['conk'],
  conk: ['conch'],
  confectionary: ['confectionery'],
  confectionery: ['confectionary'],
  conn: ['khan'],
  khan: ['conn'],
  connecter: ['connector'],
  connector: ['connecter'],
  conveyer: ['conveyor'],
  conveyor: ['conveyer'],
  coolly: ['coulee'],
  coulee: ['coolly'],
  coombes: ['coombs'],
  coombs: ['coombes'],
  coop: ['coupe'],
  coupe: ['coop'],
  cops: ['kops'],
  kops: ['cops'],
  core: ['cores', 'corps'],
  cores: ['core', 'corps'],
  corps: ['core', 'cores'],
  corespondent: ['correspondent'],
  correspondent: ['corespondent'],
  corrie: ['cory'],
  cory: ['corrie'],
  cosey: ['cosy', 'cozy'],
  cosy: ['cosey', 'cozy'],
  cozy: ['cosey', 'cosy'],
  coss: ['costs', 'koss'],
  costs: ['coss', 'koss'],
  koss: ['coss', 'costs'],
  council: ['counsel'],
  counsel: ['council'],
  councilor: ['counsellor', 'counselor'],
  counsellor: ['councilor', 'counselor'],
  counselor: ['councilor', 'counsellor'],
  councilors: ['counsellors', 'counselors'],
  counsellors: ['councilors', 'counselors'],
  counselors: ['councilors', 'counsellors'],
  councils: ['counsels'],
  counsels: ['councils'],
  coup: ['coups'],
  coups: ['coup'],
  courier: ['currier'],
  currier: ['courier'],
  courter: ['quarter'],
  quarter: ['courter'],
  craft: ['kraft'],
  kraft: ['craft'],
  crappie: ['crappy'],
  crappy: ['crappie'],
  creak: ['creek'],
  creek: ['creak'],
  cream: ['creme'],
  creme: ['cream'],
  cress: ['crests'],
  crests: ['cress'],
  crewel: ['cruel'],
  cruel: ['crewel'],
  crews: ['cruise', 'cruse'],
  cruise: ['crews', 'cruse'],
  cruse: ['crews', 'cruise'],
  cris: ['kris'],
  kris: ['cris'],
  croc: ['crock'],
  crock: ['croc'],
  croon: ['kroon'],
  kroon: ['croon'],
  cruiser: ['kreuzer'],
  kreuzer: ['cruiser'],
  cues: ['queues'],
  queues: ['cues'],
  cuing: ['queuing'],
  queuing: ['cuing'],
  curb: ['kerb'],
  kerb: ['curb'],
  curbs: ['kerbs'],
  kerbs: ['curbs'],
  currie: ['curry'],
  curry: ['currie'],
  cymbal: ['symbol'],
  symbol: ['cymbal'],
  cymbals: ['symbols'],
  symbols: ['cymbals'],
  cypress: ['cyprus'],
  cyprus: ['cypress'],
  czar: ['tsar'],
  tsar: ['czar'],
  daemon: ['daman', 'demon'],
  daman: ['daemon', 'demon'],
  demon: ['daemon', 'daman'],
  dahl: ['doll'],
  doll: ['dahl'],
  dairy: ['derry'],
  derry: ['dairy'],
  dais: ['days', 'daze'],
  days: ['dais', 'daze'],
  daze: ['dais', 'days'],
  dammed: ['damned'],
  damned: ['dammed'],
  damming: ['damning'],
  damning: ['damming'],
  damns: ['dams'],
  dams: ['damns'],
  daub: ['daube'],
  daube: ['daub'],
  deal: ['diel'],
  diel: ['deal'],
  deans: ['denes'],
  denes: ['deans'],
  dear: ['deer'],
  deer: ['dear'],
  defence: ['defense'],
  defense: ['defence'],
  defer: ['differ'],
  differ: ['defer'],
  deferred: ['differed'],
  differed: ['deferred'],
  deferring: ['differing'],
  differing: ['deferring'],
  defers: ['differs'],
  differs: ['defers'],
  defuse: ['diffuse'],
  diffuse: ['defuse'],
  defused: ['diffused'],
  diffused: ['defused'],
  defusing: ['diffusing'],
  diffusing: ['defusing'],
  demur: ['dimmer'],
  dimmer: ['demur'],
  demurs: ['dimmers'],
  dimmers: ['demurs'],
  depravation: ['deprivation'],
  deprivation: ['depravation'],
  descendant: ['descendent'],
  descendent: ['descendant'],
  descendants: ['descendents'],
  descendents: ['descendants'],
  descent: ['dissent'],
  dissent: ['descent'],
  descents: ['dissents'],
  dissents: ['descents'],
  desert: ['dessert'],
  dessert: ['desert'],
  deserts: ['desserts'],
  desserts: ['deserts'],
  deuce: ['duce'],
  duce: ['deuce'],
  device: ['devise'],
  devise: ['device'],
  dewing: ['doing'],
  doing: ['dewing'],
  dews: ['dues'],
  dues: ['dews'],
  dhole: ['dole'],
  dole: ['dhole'],
  dialog: ['dialogue'],
  dialogue: ['dialog'],
  diarrhea: ['diarrhoea'],
  diarrhoea: ['diarrhea'],
  dickey: ['dickie', 'dicky'],
  dickie: ['dickey', 'dicky'],
  dicky: ['dickey', 'dickie'],
  died: ['dyed'],
  dyed: ['died'],
  dies: ['dyes'],
  dyes: ['dies'],
  dietician: ['dietitian'],
  dietitian: ['dietician'],
  dike: ['dyke'],
  dyke: ['dike'],
  dikes: ['dykes'],
  dykes: ['dikes'],
  dinars: ['diners'],
  diners: ['dinars'],
  dines: ['dynes'],
  dynes: ['dines'],
  diocese: ['dioceses'],
  dioceses: ['diocese'],
  dire: ['dyer'],
  dyer: ['dire'],
  disabilities: ['disability'],
  disability: ['disabilities'],
  disc: ['disk'],
  disk: ['disc'],
  discreet: ['discrete'],
  discrete: ['discreet'],
  discs: ['disks'],
  disks: ['discs'],
  discus: ['discuss'],
  discuss: ['discus'],
  distil: ['distill'],
  distill: ['distil'],
  doggie: ['doggy'],
  doggy: ['doggie'],
  dolls: ['dols'],
  dols: ['dolls'],
  done: ['donne'],
  donne: ['done'],
  donut: ['doughnut'],
  doughnut: ['donut'],
  donuts: ['doughnuts'],
  doughnuts: ['donuts'],
  door: ['dore', 'dorr'],
  dore: ['door', 'dorr'],
  dorr: ['door', 'dore'],
  dour: ['dower'],
  dower: ['dour'],
  douse: ['dowse'],
  dowse: ['douse'],
  dousing: ['dowsing'],
  dowsing: ['dousing'],
  doxie: ['doxy'],
  doxy: ['doxie'],
  draft: ['draught'],
  draught: ['draft'],
  draftee: ['drafty'],
  drafty: ['draftee'],
  drafts: ['draughts'],
  draughts: ['drafts'],
  draftsman: ['draftsmen'],
  draftsmen: ['draftsman'],
  drier: ['dryer'],
  dryer: ['drier'],
  droop: ['drupe'],
  drupe: ['droop'],
  dual: ['duel'],
  duel: ['dual'],
  dualist: ['duelist'],
  duelist: ['dualist'],
  duals: ['duels'],
  duels: ['duals'],
  ducked: ['duct'],
  duct: ['ducked'],
  dyeing: ['dying'],
  dying: ['dyeing'],
  eager: ['eger'],
  eger: ['eager'],
  earn: ['erne'],
  erne: ['earn'],
  eaux: ['owes'],
  owes: ['eaux'],
  eaves: ['eves'],
  eves: ['eaves'],
  echoes: ['echos'],
  echos: ['echoes'],
  eide: ['eyed'],
  eyed: ['eide'],
  elusive: ['illusive'],
  illusive: ['elusive'],
  embed: ['imbed'],
  imbed: ['embed'],
  emersed: ['immersed'],
  immersed: ['emersed'],
  empanel: ['impanel'],
  impanel: ['empanel'],
  empaneled: ['impaneled'],
  impaneled: ['empaneled'],
  enclosure: ['inclosure'],
  inclosure: ['enclosure'],
  encyclopaedia: ['encyclopedia'],
  encyclopedia: ['encyclopaedia'],
  endeavor: ['endeavour'],
  endeavour: ['endeavor'],
  ensure: ['insure'],
  insure: ['ensure'],
  ensured: ['insured'],
  insured: ['ensured'],
  ensures: ['insures'],
  insures: ['ensures'],
  ensuring: ['insuring'],
  insuring: ['ensuring'],
  estrous: ['estrus'],
  estrus: ['estrous'],
  ewes: ['youse'],
  youse: ['ewes'],
  eyre: ['heir'],
  heir: ['eyre'],
  fade: ['fayed'],
  fayed: ['fade'],
  fain: ['fane', 'feign'],
  fane: ['fain', 'feign'],
  feign: ['fain', 'fane'],
  faint: ['feint'],
  feint: ['faint'],
  fair: ['fare'],
  fare: ['fair'],
  fairies: ['ferries'],
  ferries: ['fairies'],
  fairs: ['fares'],
  fares: ['fairs'],
  fairy: ['ferry'],
  ferry: ['fairy'],
  faro: ['farrow', 'pharaoh'],
  farrow: ['faro', 'pharaoh'],
  pharaoh: ['faro', 'farrow'],
  fate: ['fete'],
  fete: ['fate'],
  fated: ['feted'],
  feted: ['fated'],
  faze: ['phase'],
  phase: ['faze'],
  fazed: ['phased'],
  phased: ['fazed'],
  feat: ['feet'],
  feet: ['feat'],
  fennel: ['phenol'],
  phenol: ['fennel'],
  fiber: ['fibre'],
  fibre: ['fiber'],
  fiberboard: ['fibreboard'],
  fibreboard: ['fiberboard'],
  fila: ['phyla'],
  phyla: ['fila'],
  file: ['phyle'],
  phyle: ['file'],
  find: ['fined'],
  fined: ['find'],
  fireman: ['firemen'],
  firemen: ['fireman'],
  firm: ['from'],
  from: ['firm'],
  firs: ['furs'],
  furs: ['firs'],
  fisher: ['fissure'],
  fissure: ['fisher'],
  fishers: ['fissures'],
  fissures: ['fishers'],
  flack: ['flak'],
  flak: ['flack'],
  flair: ['flare'],
  flare: ['flair'],
  flea: ['flee'],
  flee: ['flea'],
  fleas: ['flees'],
  flees: ['fleas'],
  flecks: ['flex'],
  flex: ['flecks'],
  flew: ['flue'],
  flue: ['flew'],
  flier: ['flyer'],
  flyer: ['flier'],
  fliers: ['flyers'],
  flyers: ['fliers'],
  floc: ['flock'],
  flock: ['floc'],
  floe: ['flow'],
  flow: ['floe'],
  flour: ['flower'],
  flower: ['flour'],
  flours: ['flowers'],
  flowers: ['flours'],
  focused: ['focussed'],
  focussed: ['focused'],
  force: ['fourths'],
  fourths: ['force'],
  fore: ['four'],
  four: ['fore'],
  forego: ['forgo'],
  forgo: ['forego'],
  foregoing: ['forgoing'],
  forgoing: ['foregoing'],
  foreigner: ['forerunner'],
  forerunner: ['foreigner'],
  foreigners: ['forerunners'],
  forerunners: ['foreigners'],
  foreman: ['foremen'],
  foremen: ['foreman'],
  foreword: ['forward'],
  forward: ['foreword'],
  fort: ['forte'],
  forte: ['fort'],
  fortes: ['forts'],
  forts: ['fortes'],
  forth: ['fourth'],
  fourth: ['forth'],
  foss: ['fosse'],
  fosse: ['foss'],
  foul: ['fowl'],
  fowl: ['foul'],
  franc: ['frank'],
  frank: ['franc'],
  francs: ['franks'],
  franks: ['francs'],
  frater: ['freighter'],
  freighter: ['frater'],
  freed: ['fried'],
  fried: ['freed'],
  frees: ['freeze', 'frieze'],
  freeze: ['frees', 'frieze'],
  frieze: ['frees', 'freeze'],
  freezes: ['friezes'],
  friezes: ['freezes'],
  friar: ['frier', 'fryer'],
  frier: ['friar', 'fryer'],
  fryer: ['friar', 'frier'],
  friars: ['fryers'],
  fryers: ['friars'],
  frits: ['fritts', 'fritz'],
  fritts: ['frits', 'fritz'],
  fritz: ['frits', 'fritts'],
  fueled: ['fuelled'],
  fuelled: ['fueled'],
  fueling: ['fuelling'],
  fuelling: ['fueling'],
  fuses: ['fuzes'],
  fuzes: ['fuses'],
  gabby: ['gaby'],
  gaby: ['gabby'],
  gaff: ['gaffe'],
  gaffe: ['gaff'],
  gage: ['gauge'],
  gauge: ['gage'],
  gait: ['gate'],
  gate: ['gait'],
  gaiter: ['gator'],
  gator: ['gaiter'],
  gantlet: ['gauntlet'],
  gauntlet: ['gantlet'],
  gases: ['gasses'],
  gasses: ['gases'],
  gassed: ['gast'],
  gast: ['gassed'],
  gays: ['gaze'],
  gaze: ['gays'],
  geez: ['jees', 'jeez'],
  jees: ['geez', 'jeez'],
  jeez: ['geez', 'jees'],
  gene: ['jean'],
  jean: ['gene'],
  genes: ['jeans'],
  jeans: ['genes'],
  gest: ['jest'],
  jest: ['gest'],
  gibe: ['jibe'],
  jibe: ['gibe'],
  gibes: ['jibes'],
  jibes: ['gibes'],
  gild: ['guild'],
  guild: ['gild'],
  gilder: ['guilder'],
  guilder: ['gilder'],
  gillie: ['gilly'],
  gilly: ['gillie'],
  gilt: ['guilt'],
  guilt: ['gilt'],
  gist: ['just'],
  just: ['gist'],
  glamor: ['glamour'],
  glamour: ['glamor'],
  gneiss: ['nice', 'niece'],
  nice: ['gneiss', 'niece'],
  niece: ['gneiss', 'nice'],
  gnome: ['nome'],
  nome: ['gnome'],
  goddam: ['goddamn'],
  goddamn: ['goddam'],
  goodby: ['goodbye'],
  goodbye: ['goodby'],
  goodie: ['goody'],
  goody: ['goodie'],
  gored: ['gourd'],
  gourd: ['gored'],
  gorilla: ['guerilla', 'guerrilla'],
  guerilla: ['gorilla', 'guerrilla'],
  guerrilla: ['gorilla', 'guerilla'],
  gorillas: ['guerillas', 'guerrillas'],
  guerillas: ['gorillas', 'guerrillas'],
  guerrillas: ['gorillas', 'guerillas'],
  graham: ['gram'],
  gram: ['graham'],
  grahams: ['grams'],
  grams: ['grahams'],
  grate: ['great'],
  great: ['grate'],
  grater: ['greater'],
  greater: ['grater'],
  grates: ['greats'],
  greats: ['grates'],
  gray: ['grey'],
  grey: ['gray'],
  graying: ['greying'],
  greying: ['graying'],
  grays: ['graze'],
  graze: ['grays'],
  greave: ['grieve'],
  grieve: ['greave'],
  greaves: ['grieves'],
  grieves: ['greaves'],
  grill: ['grille'],
  grille: ['grill'],
  grimaced: ['grimmest'],
  grimmest: ['grimaced'],
  grisly: ['grizzly'],
  grizzly: ['grisly'],
  groan: ['grown'],
  grown: ['groan'],
  grocer: ['grosser'],
  grosser: ['grocer'],
  gross: ['grosz'],
  grosz: ['gross'],
  guarantee: ['guaranty'],
  guaranty: ['guarantee'],
  guarantees: ['guaranties'],
  guaranties: ['guarantees'],
  guess: ['guests'],
  guests: ['guess'],
  guessed: ['guest'],
  guest: ['guessed'],
  guise: ['guys'],
  guys: ['guise'],
  gulley: ['gully'],
  gully: ['gulley'],
  gussie: ['gussy'],
  gussy: ['gussie'],
  haik: ['hake'],
  hake: ['haik'],
  hail: ['hale'],
  hale: ['hail'],
  hails: ['hales'],
  hales: ['hails'],
  hair: ['hare'],
  hare: ['hair'],
  hairs: ['hares'],
  hares: ['hairs'],
  hairy: ['harry'],
  harry: ['hairy'],
  hakeem: ['hakim'],
  hakim: ['hakeem'],
  hall: ['haul'],
  haul: ['hall'],
  halls: ['hauls'],
  hauls: ['halls'],
  halve: ['have'],
  have: ['halve'],
  halves: ['haves'],
  haves: ['halves'],
  halving: ['having'],
  having: ['halving'],
  handsome: ['hansom'],
  hansom: ['handsome'],
  hangar: ['hanger'],
  hanger: ['hangar'],
  hangars: ['hangers'],
  hangers: ['hangars'],
  harbor: ['harbour'],
  harbour: ['harbor'],
  haring: ['herring'],
  herring: ['haring'],
  hart: ['heart'],
  heart: ['hart'],
  harts: ['hearts'],
  hearts: ['harts'],
  hassel: ['hassle'],
  hassle: ['hassel'],
  hays: ['haze'],
  haze: ['hays'],
  headdress: ['headrests'],
  headrests: ['headdress'],
  heal: ['heel'],
  heel: ['heal'],
  healed: ['heeled'],
  heeled: ['healed'],
  healing: ['heeling'],
  heeling: ['healing'],
  heals: ['heels'],
  heels: ['heals'],
  hear: ['here'],
  here: ['hear'],
  heard: ['herd'],
  herd: ['heard'],
  height: ['hight'],
  hight: ['height'],
  henchman: ['henchmen'],
  henchmen: ['henchman'],
  herl: ['hurl'],
  hurl: ['herl'],
  heroes: ['heros'],
  heros: ['heroes'],
  heroin: ['heroine'],
  heroine: ['heroin'],
  hertz: ['hurts'],
  hurts: ['hertz'],
  hews: ['hues'],
  hues: ['hews'],
  hiccough: ['hiccup'],
  hiccup: ['hiccough'],
  hiccoughs: ['hiccups'],
  hiccups: ['hiccoughs'],
  higher: ['hire'],
  hire: ['higher'],
  hoagie: ['hoagy'],
  hoagy: ['hoagie'],
  hoar: ['whore'],
  whore: ['hoar'],
  hoard: ['horde'],
  horde: ['hoard'],
  hoards: ['hordes'],
  hordes: ['hoards'],
  hoarse: ['horse'],
  horse: ['hoarse'],
  hoes: ['hose'],
  hose: ['hoes'],
  hold: ['holed'],
  holed: ['hold'],
  hole: ['whole'],
  whole: ['hole'],
  holes: ['wholes'],
  wholes: ['holes'],
  hollo: ['hollow'],
  hollow: ['hollo'],
  holm: ['home'],
  home: ['holm'],
  holy: ['wholly'],
  wholly: ['holy'],
  horsed: ['horst'],
  horst: ['horsed'],
  horseman: ['horsemen'],
  horsemen: ['horseman'],
  hostel: ['hostile'],
  hostile: ['hostel'],
  humerus: ['humorous'],
  humorous: ['humerus'],
  hurley: ['hurly'],
  hurly: ['hurley'],
  hysterectomies: ['hysterectomy'],
  hysterectomy: ['hysterectomies'],
  icon: ['ikon'],
  ikon: ['icon'],
  idle: ['idol', 'idyll'],
  idol: ['idle', 'idyll'],
  idyll: ['idle', 'idol'],
  idles: ['idols'],
  idols: ['idles'],
  immanence: ['imminence'],
  imminence: ['immanence'],
  immanent: ['imminent'],
  imminent: ['immanent'],
  incite: ['insight'],
  insight: ['incite'],
  incites: ['insights'],
  insights: ['incites'],
  indict: ['indite'],
  indite: ['indict'],
  indicted: ['indited'],
  indited: ['indicted'],
  infantryman: ['infantrymen'],
  infantrymen: ['infantryman'],
  initialing: ['initialling'],
  initialling: ['initialing'],
  innuendoes: ['innuendos'],
  innuendos: ['innuendoes'],
  jacinth: ['jacinthe'],
  jacinthe: ['jacinth'],
  jasmin: ['jasmine', 'jazzmen'],
  jasmine: ['jasmin', 'jazzmen'],
  jazzmen: ['jasmin', 'jasmine'],
  jewel: ['joule'],
  joule: ['jewel'],
  jewelers: ['jewellers'],
  jewellers: ['jewelers'],
  jewels: ['joules'],
  joules: ['jewels'],
  jinks: ['jinx'],
  jinx: ['jinks'],
  judgement: ['judgment'],
  judgment: ['judgement'],
  judgements: ['judgments'],
  judgments: ['judgements'],
  junkie: ['junky'],
  junky: ['junkie'],
  kail: ['kale'],
  kale: ['kail'],
  keas: ['keys'],
  keys: ['keas'],
  keef: ['kief'],
  kief: ['keef'],
  keelson: ['kelson'],
  kelson: ['keelson'],
  kern: ['kirn'],
  kirn: ['kern'],
  kernes: ['kerns'],
  kerns: ['kernes'],
  kiddie: ['kiddy'],
  kiddy: ['kiddie'],
  kidnaped: ['kidnapped'],
  kidnapped: ['kidnaped'],
  kidnaping: ['kidnapping'],
  kidnapping: ['kidnaping'],
  kimchee: ['kimchi'],
  kimchi: ['kimchee'],
  kinds: ['kines'],
  kines: ['kinds'],
  kissed: ['kist'],
  kist: ['kissed'],
  kite: ['kyte'],
  kyte: ['kite'],
  kittel: ['kittle'],
  kittle: ['kittel'],
  knapper: ['napper'],
  napper: ['knapper'],
  knave: ['nave'],
  nave: ['knave'],
  knead: ['kneed', 'need'],
  kneed: ['knead', 'need'],
  need: ['knead', 'kneed'],
  kneading: ['needing'],
  needing: ['kneading'],
  knight: ['night', 'nite'],
  night: ['knight', 'nite'],
  nite: ['knight', 'night'],
  knightly: ['nightly'],
  nightly: ['knightly'],
  knights: ['nights'],
  nights: ['knights'],
  knock: ['nock'],
  nock: ['knock'],
  knows: ['noes', 'nose'],
  noes: ['knows', 'nose'],
  nose: ['knows', 'noes'],
  koto: ['kowtow'],
  kowtow: ['koto'],
  krona: ['krone'],
  krone: ['krona'],
  kroner: ['kronor'],
  kronor: ['kroner'],
  labeled: ['labelled'],
  labelled: ['labeled'],
  labor: ['labour'],
  labour: ['labor'],
  lacey: ['lacy'],
  lacy: ['lacey'],
  lade: ['laid'],
  laid: ['lade'],
  lager: ['logger'],
  logger: ['lager'],
  lain: ['lane'],
  lane: ['lain'],
  lair: ['lehr'],
  lehr: ['lair'],
  lama: ['llama'],
  llama: ['lama'],
  lamas: ['llamas'],
  llamas: ['lamas'],
  lambie: ['lamby'],
  lamby: ['lambie'],
  laps: ['lapse'],
  lapse: ['laps'],
  lase: ['lays', 'leis', 'leys'],
  lays: ['lase', 'leis', 'leys'],
  leis: ['lase', 'lays', 'leys'],
  leys: ['lase', 'lays', 'leis'],
  laser: ['lazar'],
  lazar: ['laser'],
  lass: ['last', 'lost'],
  last: ['lass', 'lost'],
  lost: ['lass', 'last'],
  lats: ['lots', 'lottes'],
  lots: ['lats', 'lottes'],
  lottes: ['lats', 'lots'],
  lauder: ['louder'],
  louder: ['lauder'],
  laugher: ['locker'],
  locker: ['laugher'],
  laurel: ['loral'],
  loral: ['laurel'],
  layman: ['laymen'],
  laymen: ['layman'],
  leach: ['leech'],
  leech: ['leach'],
  leaches: ['leeches'],
  leeches: ['leaches'],
  leader: ['lieder'],
  lieder: ['leader'],
  leaf: ['lief'],
  lief: ['leaf'],
  leak: ['leek'],
  leek: ['leak'],
  leaks: ['leeks'],
  leeks: ['leaks'],
  lean: ['lien'],
  lien: ['lean'],
  leans: ['liens'],
  liens: ['leans'],
  leaped: ['leapt'],
  leapt: ['leaped'],
  leary: ['leery'],
  leery: ['leary'],
  leas: ['lees'],
  lees: ['leas'],
  leased: ['least'],
  least: ['leased'],
  leaver: ['lever'],
  lever: ['leaver'],
  leavy: ['levee', 'levy'],
  levee: ['leavy', 'levy'],
  levy: ['leavy', 'levee'],
  ledger: ['leger'],
  leger: ['ledger'],
  lemans: ['lemons'],
  lemons: ['lemans'],
  leno: ['lino'],
  lino: ['leno'],
  lessen: ['lesson'],
  lesson: ['lessen'],
  lessens: ['lessons'],
  lessons: ['lessens'],
  lesser: ['lessor'],
  lessor: ['lesser'],
  levees: ['levies'],
  levies: ['levees'],
  leveled: ['levelled'],
  levelled: ['leveled'],
  lewis: ['louie', 'louis'],
  louie: ['lewis', 'louis'],
  louis: ['lewis', 'louie'],
  licence: ['license'],
  license: ['licence'],
  licences: ['licenses'],
  licenses: ['licences'],
  licenser: ['licensor'],
  licensor: ['licenser'],
  lichen: ['liken'],
  liken: ['lichen'],
  lichens: ['likens'],
  likens: ['lichens'],
  licht: ['licked'],
  licked: ['licht'],
  licker: ['liqueur', 'liquor'],
  liqueur: ['licker', 'liquor'],
  liquor: ['licker', 'liqueur'],
  light: ['lite'],
  lite: ['light'],
  likable: ['likeable'],
  likeable: ['likable'],
  lineman: ['linemen'],
  linemen: ['lineman'],
  links: ['lynx'],
  lynx: ['links'],
  liqueurs: ['liquors'],
  liquors: ['liqueurs'],
  lira: ['lire'],
  lire: ['lira'],
  literal: ['littoral'],
  littoral: ['literal'],
  load: ['lode'],
  lode: ['load'],
  loads: ['lodes'],
  lodes: ['loads'],
  loan: ['lone'],
  lone: ['loan'],
  loch: ['lock'],
  lock: ['loch'],
  locus: ['locusts'],
  locusts: ['locus'],
  looney: ['loony'],
  loony: ['looney'],
  loop: ['loup', 'loupe'],
  loup: ['loop', 'loupe'],
  loupe: ['loop', 'loup'],
  loos: ['lose'],
  lose: ['loos'],
  loose: ['luce'],
  luce: ['loose'],
  loot: ['lute'],
  lute: ['loot'],
  lorry: ['lory'],
  lory: ['lorry'],
  loves: ['luvs'],
  luvs: ['loves'],
  lowes: ['lows'],
  lows: ['lowes'],
  luckie: ['lucky'],
  lucky: ['luckie'],
  luster: ['lustre'],
  lustre: ['luster'],
  mach: ['mock'],
  mock: ['mach'],
  mache: ['match'],
  match: ['mache'],
  macks: ['macs'],
  macs: ['macks'],
  madam: ['madame'],
  madame: ['madam'],
  made: ['maid'],
  maid: ['made'],
  maes: ['maize', 'mays', 'maze'],
  maize: ['maes', 'mays', 'maze'],
  mays: ['maes', 'maize', 'maze'],
  maze: ['maes', 'maize', 'mays'],
  magnate: ['magnet'],
  magnet: ['magnate'],
  mail: ['maile', 'male'],
  maile: ['mail', 'male'],
  male: ['mail', 'maile'],
  mails: ['males'],
  males: ['mails'],
  main: ['mane'],
  mane: ['main'],
  mains: ['manes'],
  manes: ['mains'],
  mair: ['mare'],
  mare: ['mair'],
  mairs: ['mares'],
  mares: ['mairs'],
  mall: ['maul'],
  maul: ['mall'],
  mama: ['mamma', 'momma'],
  mamma: ['mama', 'momma'],
  momma: ['mama', 'mamma'],
  manila: ['manilla'],
  manilla: ['manila'],
  manner: ['manor'],
  manor: ['manner'],
  manners: ['manors'],
  manors: ['manners'],
  mantel: ['mantle'],
  mantle: ['mantel'],
  marc: ['mark', 'marque'],
  mark: ['marc', 'marque'],
  marque: ['marc', 'mark'],
  marks: ['marques'],
  marques: ['marks'],
  marquee: ['marquis'],
  marquis: ['marquee'],
  marry: ['merry'],
  merry: ['marry'],
  marshal: ['marshall', 'martial'],
  marshall: ['marshal', 'martial'],
  martial: ['marshal', 'marshall'],
  marshaled: ['marshalled'],
  marshalled: ['marshaled'],
  marten: ['martin'],
  martin: ['marten'],
  maser: ['mazer'],
  mazer: ['maser'],
  mass: ['masse'],
  masse: ['mass'],
  massed: ['mast'],
  mast: ['massed'],
  mater: ['matter'],
  matter: ['mater'],
  mats: ['mattes', 'matts'],
  mattes: ['mats', 'matts'],
  matts: ['mats', 'mattes'],
  matt: ['matte'],
  matte: ['matt'],
  mean: ['mien'],
  mien: ['mean'],
  meat: ['meet', 'mete'],
  meet: ['meat', 'mete'],
  mete: ['meat', 'meet'],
  meatier: ['meteor'],
  meteor: ['meatier'],
  meats: ['meets'],
  meets: ['meats'],
  medal: ['meddle'],
  meddle: ['medal'],
  merk: ['murk'],
  murk: ['merk'],
  merl: ['merle'],
  merle: ['merl'],
  metal: ['mettle'],
  mettle: ['metal'],
  midst: ['missed', 'mist'],
  missed: ['midst', 'mist'],
  mist: ['midst', 'missed'],
  might: ['mite'],
  mite: ['might'],
  mill: ['mille'],
  mille: ['mill'],
  mills: ['mils'],
  mils: ['mills'],
  mind: ['mined'],
  mined: ['mind'],
  miner: ['minor'],
  minor: ['miner'],
  miners: ['minors'],
  minors: ['miners'],
  mini: ['minny'],
  minny: ['mini'],
  mink: ['minke'],
  minke: ['mink'],
  minutia: ['minutiae'],
  minutiae: ['minutia'],
  missal: ['missel', 'missile'],
  missel: ['missal', 'missile'],
  missile: ['missal', 'missel'],
  misses: ['missus'],
  missus: ['misses'],
  mistress: ['mistrusts'],
  mistrusts: ['mistress'],
  miter: ['mitre'],
  mitre: ['miter'],
  moat: ['mote'],
  mote: ['moat'],
  moats: ['motes'],
  motes: ['moats'],
  mode: ['mowed'],
  mowed: ['mode'],
  mold: ['mould'],
  mould: ['mold'],
  molder: ['moulder'],
  moulder: ['molder'],
  molding: ['moulding'],
  moulding: ['molding'],
  moldings: ['mouldings'],
  mouldings: ['moldings'],
  molds: ['moulds'],
  moulds: ['molds'],
  moldy: ['mouldy'],
  mouldy: ['moldy'],
  mollie: ['molly'],
  molly: ['mollie'],
  moneyed: ['monied'],
  monied: ['moneyed'],
  moneys: ['monies'],
  monies: ['moneys'],
  moose: ['mousse'],
  mousse: ['moose'],
  morays: ['mores'],
  mores: ['morays'],
  morgan: ['morgen'],
  morgen: ['morgan'],
  morn: ['mourn'],
  mourn: ['morn'],
  morning: ['mourning'],
  mourning: ['morning'],
  morro: ['morrow'],
  morrow: ['morro'],
  mosk: ['mosque'],
  mosque: ['mosk'],
  mosquitoes: ['mosquitos'],
  mosquitos: ['mosquitoes'],
  mots: ['motts'],
  motts: ['mots'],
  mott: ['motte'],
  motte: ['mott'],
  moustache: ['mustache'],
  mustache: ['moustache'],
  much: ['mutch'],
  mutch: ['much'],
  mucous: ['mucus'],
  mucus: ['mucous'],
  mujahedeen: ['mujahideen'],
  mujahideen: ['mujahedeen'],
  murr: ['myrrh'],
  myrrh: ['murr'],
  murrey: ['murry'],
  murry: ['murrey'],
  muscle: ['mussel'],
  mussel: ['muscle'],
  muscles: ['mussels'],
  mussels: ['muscles'],
  muskie: ['musky'],
  musky: ['muskie'],
  mustard: ['mustered'],
  mustered: ['mustard'],
  naval: ['navel'],
  navel: ['naval'],
  necks: ['next'],
  next: ['necks'],
  nellie: ['nelly'],
  nelly: ['nellie'],
  nester: ['nestor'],
  nestor: ['nester'],
  nickel: ['nickle', 'nicol'],
  nickle: ['nickel', 'nicol'],
  nicol: ['nickel', 'nickle'],
  nickels: ['nickles', 'nicols'],
  nickles: ['nickels', 'nicols'],
  nicols: ['nickels', 'nickles'],
  nitroglycerin: ['nitroglycerine'],
  nitroglycerine: ['nitroglycerin'],
  noose: ['nous'],
  nous: ['noose'],
  oars: ['ores'],
  ores: ['oars'],
  oohs: ['ooze'],
  ooze: ['oohs'],
  overdo: ['overdue'],
  overdue: ['overdo'],
  oversea: ['oversee'],
  oversee: ['oversea'],
  overseas: ['oversees'],
  oversees: ['overseas'],
  paced: ['paste'],
  paste: ['paced'],
  packed: ['pact'],
  pact: ['packed'],
  packs: ['pacs', 'pacts'],
  pacs: ['packs', 'pacts'],
  pacts: ['packs', 'pacs'],
  paean: ['peon'],
  peon: ['paean'],
  paeans: ['peons'],
  peons: ['paeans'],
  pail: ['pale'],
  pale: ['pail'],
  pails: ['pales'],
  pales: ['pails'],
  pain: ['pane'],
  pane: ['pain'],
  pains: ['panes'],
  panes: ['pains'],
  pair: ['pare', 'pear'],
  pare: ['pair', 'pear'],
  pear: ['pair', 'pare'],
  paired: ['pared'],
  pared: ['paired'],
  pairing: ['paring'],
  paring: ['pairing'],
  pairs: ['pares', 'pears'],
  pares: ['pairs', 'pears'],
  pears: ['pairs', 'pares'],
  palate: ['palette', 'pallet'],
  palette: ['palate', 'pallet'],
  pallet: ['palate', 'palette'],
  palates: ['pallets'],
  pallets: ['palates'],
  pandit: ['pundit'],
  pundit: ['pandit'],
  papa: ['poppa'],
  poppa: ['papa'],
  pardee: ['pardi', 'pardy'],
  pardi: ['pardee', 'pardy'],
  pardy: ['pardee', 'pardi'],
  parish: ['perish'],
  perish: ['parish'],
  parlor: ['parlour'],
  parlour: ['parlor'],
  parry: ['perry'],
  perry: ['parry'],
  pass: ['pasts'],
  pasts: ['pass'],
  passed: ['past'],
  past: ['passed'],
  paster: ['pastor'],
  pastor: ['paster'],
  pattee: ['pattie', 'patty'],
  pattie: ['pattee', 'patty'],
  patty: ['pattee', 'pattie'],
  pause: ['paws'],
  paws: ['pause'],
  peace: ['peas', 'pease', 'piece'],
  peas: ['peace', 'pease', 'piece'],
  pease: ['peace', 'peas', 'piece'],
  piece: ['peace', 'peas', 'pease'],
  peak: ['peek', 'pique'],
  peek: ['peak', 'pique'],
  pique: ['peak', 'peek'],
  peaked: ['peeked', 'piqued'],
  peeked: ['peaked', 'piqued'],
  piqued: ['peaked', 'peeked'],
  peaking: ['peeking'],
  peeking: ['peaking'],
  peaks: ['peeks'],
  peeks: ['peaks'],
  peal: ['peel'],
  peel: ['peal'],
  peart: ['pert'],
  pert: ['peart'],
  peavey: ['peavy'],
  peavy: ['peavey'],
  pech: ['peck'],
  peck: ['pech'],
  pedal: ['peddle'],
  peddle: ['pedal'],
  pedaled: ['pedalled', 'peddled'],
  pedalled: ['pedaled', 'peddled'],
  peddled: ['pedaled', 'pedalled'],
  pedaling: ['peddling'],
  peddling: ['pedaling'],
  pedals: ['peddles'],
  peddles: ['pedals'],
  peer: ['pier'],
  pier: ['peer'],
  peers: ['piers'],
  piers: ['peers'],
  perse: ['purse'],
  purse: ['perse'],
  perses: ['purses'],
  purses: ['perses'],
  pervade: ['purveyed'],
  purveyed: ['pervade'],
  petit: ['petti', 'petty'],
  petti: ['petit', 'petty'],
  petty: ['petit', 'petti'],
  pharaohs: ['pharos'],
  pharos: ['pharaohs'],
  phoney: ['phony'],
  phony: ['phoney'],
  phosphorous: ['phosphorus'],
  phosphorus: ['phosphorous'],
  pigmy: ['pygmy'],
  pygmy: ['pigmy'],
  pinkie: ['pinky'],
  pinky: ['pinkie'],
  pistil: ['pistol'],
  pistol: ['pistil'],
  plack: ['plaque'],
  plaque: ['plack'],
  plain: ['plane'],
  plane: ['plain'],
  plainer: ['planar', 'planer'],
  planar: ['plainer', 'planer'],
  planer: ['plainer', 'planar'],
  plains: ['planes'],
  planes: ['plains'],
  plait: ['plate'],
  plate: ['plait'],
  plaited: ['plated'],
  plated: ['plaited'],
  plaiting: ['plating'],
  plating: ['plaiting'],
  plaits: ['plates'],
  plates: ['plaits'],
  pleas: ['please'],
  please: ['pleas'],
  plots: ['plotz'],
  plotz: ['plots'],
  plough: ['plow'],
  plow: ['plough'],
  ploughed: ['plowed'],
  plowed: ['ploughed'],
  ploughs: ['plows'],
  plows: ['ploughs'],
  plum: ['plumb'],
  plumb: ['plum'],
  point: ['pointe'],
  pointe: ['point'],
  pokey: ['poky'],
  poky: ['pokey'],
  pole: ['poll'],
  poll: ['pole'],
  poles: ['polls', 'pols'],
  polls: ['poles', 'pols'],
  pols: ['poles', 'polls'],
  poling: ['polling'],
  polling: ['poling'],
  pollack: ['pollock'],
  pollock: ['pollack'],
  populace: ['populous'],
  populous: ['populace'],
  pore: ['pour'],
  pour: ['pore'],
  pored: ['poured'],
  poured: ['pored'],
  pores: ['pours'],
  pours: ['pores'],
  poring: ['pouring'],
  pouring: ['poring'],
  pose: ['pows'],
  pows: ['pose'],
  pouter: ['powter'],
  powter: ['pouter'],
  praise: ['prays', 'preys'],
  prays: ['praise', 'preys'],
  preys: ['praise', 'prays'],
  pray: ['prey'],
  prey: ['pray'],
  prayed: ['preyed'],
  preyed: ['prayed'],
  prayer: ['preyer'],
  preyer: ['prayer'],
  praying: ['preying'],
  preying: ['praying'],
  premier: ['premiere'],
  premiere: ['premier'],
  premieres: ['premiers'],
  premiers: ['premieres'],
  preppie: ['preppy'],
  preppy: ['preppie'],
  pressed: ['prest'],
  prest: ['pressed'],
  pride: ['pried'],
  pried: ['pride'],
  prier: ['prior', 'pryer'],
  prior: ['prier', 'pryer'],
  pryer: ['prier', 'prior'],
  pries: ['prize'],
  prize: ['pries'],
  principal: ['principle'],
  principle: ['principal'],
  principals: ['principles'],
  principles: ['principals'],
  profit: ['prophet'],
  prophet: ['profit'],
  program: ['programme'],
  programme: ['program'],
  programing: ['programming'],
  programming: ['programing'],
  prolog: ['prologue'],
  prologue: ['prolog'],
  pros: ['prose'],
  prose: ['pros'],
  protesters: ['protestors'],
  protestors: ['protesters'],
  psalter: ['salter'],
  salter: ['psalter'],
  psalters: ['salters'],
  salters: ['psalters'],
  publically: ['publicly'],
  publicly: ['publically'],
  pulls: ['puls'],
  puls: ['pulls'],
  puris: ['purists'],
  purists: ['puris'],
  putts: ['putz'],
  putz: ['putts'],
  quai: ['quay'],
  quay: ['quai'],
  quail: ['quale'],
  quale: ['quail'],
  quarts: ['quartz'],
  quartz: ['quarts'],
  quietest: ['quietist'],
  quietist: ['quietest'],
  rack: ['wrack'],
  wrack: ['rack'],
  racked: ['wracked'],
  wracked: ['racked'],
  racket: ['racquet'],
  racquet: ['racket'],
  racking: ['wracking'],
  wracking: ['racking'],
  raid: ['rayed'],
  rayed: ['raid'],
  rails: ['rales'],
  rales: ['rails'],
  rain: ['reign', 'rein'],
  reign: ['rain', 'rein'],
  rein: ['rain', 'reign'],
  rained: ['reigned', 'reined'],
  reigned: ['rained', 'reined'],
  reined: ['rained', 'reigned'],
  raining: ['reigning', 'reining'],
  reigning: ['raining', 'reining'],
  reining: ['raining', 'reigning'],
  rains: ['reigns', 'reins'],
  reigns: ['rains', 'reins'],
  reins: ['rains', 'reigns'],
  raise: ['rase', 'rays', 'raze'],
  rase: ['raise', 'rays', 'raze'],
  rays: ['raise', 'rase', 'raze'],
  raze: ['raise', 'rase', 'rays'],
  raised: ['razed'],
  razed: ['raised'],
  raiser: ['raser', 'razor'],
  raser: ['raiser', 'razor'],
  razor: ['raiser', 'raser'],
  raisers: ['razors'],
  razors: ['raisers'],
  raising: ['razing'],
  razing: ['raising'],
  rancor: ['ranker'],
  ranker: ['rancor'],
  rapped: ['rapt', 'wrapped'],
  rapt: ['rapped', 'wrapped'],
  wrapped: ['rapped', 'rapt'],
  rappelling: ['repelling'],
  repelling: ['rappelling'],
  rapper: ['wrapper'],
  wrapper: ['rapper'],
  rappers: ['wrappers'],
  wrappers: ['rappers'],
  rapping: ['wrapping'],
  wrapping: ['rapping'],
  raps: ['wraps'],
  wraps: ['raps'],
  rath: ['wrath'],
  wrath: ['rath'],
  read: ['redd', 'reed'],
  redd: ['read', 'reed'],
  reed: ['read', 'redd'],
  readable: ['redouble'],
  redouble: ['readable'],
  reading: ['redding', 'reding'],
  redding: ['reading', 'reding'],
  reding: ['reading', 'redding'],
  reads: ['reeds'],
  reeds: ['reads'],
  reagent: ['regent'],
  regent: ['reagent'],
  reagents: ['regents'],
  regents: ['reagents'],
  real: ['reel', 'riel'],
  reel: ['real', 'riel'],
  riel: ['real', 'reel'],
  realize: ['relies'],
  relies: ['realize'],
  reave: ['reeve'],
  reeve: ['reave'],
  reaves: ['reeves'],
  reeves: ['reaves'],
  recision: ['rescission'],
  rescission: ['recision'],
  recisions: ['rescissions'],
  rescissions: ['recisions'],
  reck: ['wreck'],
  wreck: ['reck'],
  reef: ['reif'],
  reif: ['reef'],
  reek: ['wreak'],
  wreak: ['reek'],
  reeking: ['wreaking'],
  wreaking: ['reeking'],
  reeks: ['wreaks'],
  wreaks: ['reeks'],
  rees: ['reis'],
  reis: ['rees'],
  refer: ['rougher'],
  rougher: ['refer'],
  repos: ['repose'],
  repose: ['repos'],
  rest: ['wrest'],
  wrest: ['rest'],
  rested: ['wrested'],
  wrested: ['rested'],
  resting: ['wresting'],
  wresting: ['resting'],
  reveler: ['reveller'],
  reveller: ['reveler'],
  revelers: ['revellers'],
  revellers: ['revelers'],
  rhymer: ['rimer'],
  rimer: ['rhymer'],
  rhymes: ['rimes'],
  rimes: ['rhymes'],
  rials: ['riles'],
  riles: ['rials'],
  riffed: ['rift'],
  rift: ['riffed'],
  right: ['rite', 'wright', 'write'],
  rite: ['right', 'wright', 'write'],
  wright: ['right', 'rite', 'write'],
  write: ['right', 'rite', 'wright'],
  righter: ['writer'],
  writer: ['righter'],
  rights: ['rites', 'wrights', 'writes'],
  rites: ['rights', 'wrights', 'writes'],
  wrights: ['rights', 'rites', 'writes'],
  writes: ['rights', 'rites', 'wrights'],
  riley: ['wryly'],
  wryly: ['riley'],
  ring: ['wring'],
  wring: ['ring'],
  ringer: ['wringer'],
  wringer: ['ringer'],
  ringing: ['wringing'],
  wringing: ['ringing'],
  ritz: ['writs'],
  writs: ['ritz'],
  road: ['rode', 'rowed'],
  rode: ['road', 'rowed'],
  rowed: ['road', 'rode'],
  robbin: ['robin'],
  robin: ['robbin'],
  roes: ['rose', 'rows'],
  rose: ['roes', 'rows'],
  rows: ['roes', 'rose'],
  roister: ['royster'],
  royster: ['roister'],
  role: ['roll'],
  roll: ['role'],
  roles: ['rolls'],
  rolls: ['roles'],
  rood: ['rude'],
  rude: ['rood'],
  roose: ['ruse'],
  ruse: ['roose'],
  root: ['rout', 'route'],
  rout: ['root', 'route'],
  route: ['root', 'rout'],
  rooted: ['routed'],
  routed: ['rooted'],
  rooter: ['router'],
  router: ['rooter'],
  rooters: ['routers'],
  routers: ['rooters'],
  rooting: ['routing'],
  routing: ['rooting'],
  roots: ['routes'],
  routes: ['roots'],
  rote: ['wrote'],
  wrote: ['rote'],
  rouble: ['ruble'],
  ruble: ['rouble'],
  rough: ['ruff'],
  ruff: ['rough'],
  roughing: ['ruffing'],
  ruffing: ['roughing'],
  rowan: ['rowen'],
  rowen: ['rowan'],
  rumor: ['rumour'],
  rumour: ['rumor'],
  rumors: ['rumours'],
  rumours: ['rumors'],
  rung: ['wrung'],
  wrung: ['rung'],
  saber: ['sabir', 'sabre'],
  sabir: ['saber', 'sabre'],
  sabre: ['saber', 'sabir'],
  sabers: ['sabres'],
  sabres: ['sabers'],
  sacks: ['sacs'],
  sacs: ['sacks'],
  saddling: ['sandling'],
  sandling: ['saddling'],
  sail: ['sale'],
  sale: ['sail'],
  sailer: ['sailor'],
  sailor: ['sailer'],
  sails: ['sales'],
  sales: ['sails'],
  sain: ['sane'],
  sane: ['sain'],
  salable: ['saleable'],
  saleable: ['salable'],
  sall: ['saul'],
  saul: ['sall'],
  salt: ['sault'],
  sault: ['salt'],
  sari: ['sorry'],
  sorry: ['sari'],
  savanna: ['savannah'],
  savannah: ['savanna'],
  saver: ['savor'],
  savor: ['saver'],
  savers: ['savors'],
  savors: ['savers'],
  scary: ['skerry'],
  skerry: ['scary'],
  scene: ['seen'],
  seen: ['scene'],
  schilling: ['shilling'],
  shilling: ['schilling'],
  schillings: ['shillings'],
  shillings: ['schillings'],
  schtick: ['shtick'],
  shtick: ['schtick'],
  scull: ['skull'],
  skull: ['scull'],
  seal: ['seel'],
  seel: ['seal'],
  seam: ['seem'],
  seem: ['seam'],
  seaman: ['seamen', 'semen'],
  seamen: ['seaman', 'semen'],
  semen: ['seaman', 'seamen'],
  seams: ['seems'],
  seems: ['seams'],
  sear: ['sere'],
  sere: ['sear'],
  seers: ['seres'],
  seres: ['seers'],
  seidel: ['sidle'],
  sidle: ['seidel'],
  senate: ['sennet'],
  sennet: ['senate'],
  senor: ['signor'],
  signor: ['senor'],
  serf: ['surf'],
  surf: ['serf'],
  serge: ['surge'],
  surge: ['serge'],
  sewed: ['sowed'],
  sowed: ['sewed'],
  sewing: ['sowing'],
  sowing: ['sewing'],
  sewn: ['sown'],
  sown: ['sewn'],
  shanti: ['shanty'],
  shanty: ['shanti'],
  sharpie: ['sharpy'],
  sharpy: ['sharpie'],
  shaul: ['shawl'],
  shawl: ['shaul'],
  shay: ['shea'],
  shea: ['shay'],
  shear: ['sheer'],
  sheer: ['shear'],
  shew: ['shoe', 'shoo'],
  shoe: ['shew', 'shoo'],
  shoo: ['shew', 'shoe'],
  shone: ['shown'],
  shown: ['shone'],
  shop: ['shoppe'],
  shoppe: ['shop'],
  shoppes: ['shops'],
  shops: ['shoppes'],
  shot: ['shott'],
  shott: ['shot'],
  shots: ['shotts'],
  shotts: ['shots'],
  side: ['sighed'],
  sighed: ['side'],
  sighs: ['size'],
  size: ['sighs'],
  sign: ['sine'],
  sine: ['sign'],
  signaled: ['signalled'],
  signalled: ['signaled'],
  signaling: ['signalling'],
  signalling: ['signaling'],
  signs: ['sines'],
  sines: ['signs'],
  sikes: ['sykes'],
  sykes: ['sikes'],
  silva: ['sylva'],
  sylva: ['silva'],
  siphon: ['syphon'],
  syphon: ['siphon'],
  sizable: ['sizeable'],
  sizeable: ['sizable'],
  skeen: ['skene'],
  skene: ['skeen'],
  skees: ['skis'],
  skis: ['skees'],
  slay: ['sleigh'],
  sleigh: ['slay'],
  sleight: ['slight'],
  slight: ['sleight'],
  sloe: ['slow'],
  slow: ['sloe'],
  smokey: ['smoky'],
  smoky: ['smokey'],
  soar: ['sore'],
  sore: ['soar'],
  soared: ['sword'],
  sword: ['soared'],
  soars: ['sores'],
  sores: ['soars'],
  solan: ['solon'],
  solon: ['solan'],
  sole: ['soul'],
  soul: ['sole'],
  soles: ['souls'],
  souls: ['soles'],
  sonny: ['sunny'],
  sunny: ['sonny'],
  sons: ['suns'],
  suns: ['sons'],
  sorel: ['sorrel'],
  sorrel: ['sorel'],
  sous: ['sues'],
  sues: ['sous'],
  souter: ['suiter', 'suitor'],
  suiter: ['souter', 'suitor'],
  suitor: ['souter', 'suiter'],
  sovereign: ['sovran'],
  sovran: ['sovereign'],
  sovereigns: ['sovrans'],
  sovrans: ['sovereigns'],
  spacial: ['spatial'],
  spatial: ['spacial'],
  spear: ['speer', 'speir'],
  speer: ['spear', 'speir'],
  speir: ['spear', 'speer'],
  spears: ['speirs'],
  speirs: ['spears'],
  spec: ['speck'],
  speck: ['spec'],
  specialities: ['specialties'],
  specialties: ['specialities'],
  specks: ['specs'],
  specs: ['specks'],
  specter: ['spectre'],
  spectre: ['specter'],
  spicey: ['spicy'],
  spicy: ['spicey'],
  spiraling: ['spiralling'],
  spiralling: ['spiraling'],
  spits: ['spitz'],
  spitz: ['spits'],
  spring: ['spurring'],
  spurring: ['spring'],
  stade: ['staid', 'stayed'],
  staid: ['stade', 'stayed'],
  stayed: ['stade', 'staid'],
  staff: ['staph'],
  staph: ['staff'],
  stair: ['stare'],
  stare: ['stair'],
  stairs: ['stares'],
  stares: ['stairs'],
  stake: ['steak'],
  steak: ['stake'],
  stakes: ['steaks'],
  steaks: ['stakes'],
  stationary: ['stationery'],
  stationery: ['stationary'],
  steal: ['steel'],
  steel: ['steal'],
  steals: ['steels'],
  steels: ['steals'],
  step: ['steppe'],
  steppe: ['step'],
  steppes: ['steps'],
  steps: ['steppes'],
  stich: ['stitch'],
  stitch: ['stich'],
  stile: ['style'],
  style: ['stile'],
  stiles: ['styles'],
  styles: ['stiles'],
  stoney: ['stony'],
  stony: ['stoney'],
  stoop: ['stoup'],
  stoup: ['stoop'],
  storey: ['story'],
  story: ['storey'],
  straight: ['strait'],
  strait: ['straight'],
  straights: ['straits'],
  straits: ['straights'],
  succor: ['sucker'],
  sucker: ['succor'],
  suede: ['swayed'],
  swayed: ['suede'],
  suite: ['sweet'],
  sweet: ['suite'],
  suites: ['sweets'],
  sweets: ['suites'],
  sulfate: ['sulphate'],
  sulphate: ['sulfate'],
  sulfur: ['sulphur'],
  sulphur: ['sulfur'],
  swails: ['swales'],
  swales: ['swails'],
  taber: ['tabor'],
  tabor: ['taber'],
  tableau: ['tableaux'],
  tableaux: ['tableau'],
  tacked: ['tact'],
  tact: ['tacked'],
  tail: ['tale'],
  tale: ['tail'],
  tails: ['tales'],
  tales: ['tails'],
  talkie: ['talky'],
  talky: ['talkie'],
  tammie: ['tammy'],
  tammy: ['tammie'],
  tarry: ['terry'],
  terry: ['tarry'],
  tartar: ['tarter'],
  tarter: ['tartar'],
  tatar: ['tatter'],
  tatter: ['tatar'],
  tatars: ['tatters'],
  tatters: ['tatars'],
  taught: ['taut'],
  taut: ['taught'],
  teal: ['teel'],
  teel: ['teal'],
  team: ['teem'],
  teem: ['team'],
  teaming: ['teeming'],
  teeming: ['teaming'],
  teams: ['teems'],
  teems: ['teams'],
  teas: ['tease', 'tees'],
  tease: ['teas', 'tees'],
  tees: ['teas', 'tease'],
  tele: ['telly'],
  telly: ['tele'],
  tenner: ['tenor'],
  tenor: ['tenner'],
  ternes: ['terns', 'turns'],
  terns: ['ternes', 'turns'],
  turns: ['ternes', 'terns'],
  testes: ['tests'],
  tests: ['testes'],
  theater: ['theatre'],
  theatre: ['theater'],
  theaters: ['theatres'],
  theatres: ['theaters'],
  their: ['there'],
  there: ['their'],
  thoro: ['thorough'],
  thorough: ['thoro'],
  thorp: ['thorpe'],
  thorpe: ['thorp'],
  threw: ['through', 'thru'],
  through: ['threw', 'thru'],
  thru: ['threw', 'through'],
  throes: ['throws'],
  throws: ['throes'],
  throne: ['thrown'],
  thrown: ['throne'],
  throughway: ['thruway'],
  thruway: ['throughway'],
  ticks: ['tics'],
  tics: ['ticks'],
  tide: ['tied'],
  tied: ['tide'],
  tieing: ['tying'],
  tying: ['tieing'],
  tighten: ['titan'],
  titan: ['tighten'],
  tightens: ['titans'],
  titans: ['tightens'],
  tike: ['tyke'],
  tyke: ['tike'],
  timber: ['timbre'],
  timbre: ['timber'],
  tine: ['tyne'],
  tyne: ['tine'],
  tines: ['tynes'],
  tynes: ['tines'],
  tire: ['tyer'],
  tyer: ['tire'],
  toad: ['toed', 'towed'],
  toed: ['toad', 'towed'],
  towed: ['toad', 'toed'],
  toeing: ['towing'],
  towing: ['toeing'],
  toes: ['tows'],
  tows: ['toes'],
  told: ['tolled'],
  tolled: ['told'],
  tole: ['toll'],
  toll: ['tole'],
  toles: ['tolls'],
  tolls: ['toles'],
  toney: ['tony'],
  tony: ['toney'],
  tongue: ['tung'],
  tung: ['tongue'],
  tonnes: ['tons'],
  tons: ['tonnes'],
  toon: ['tune'],
  tune: ['toon'],
  topography: ['typography'],
  typography: ['topography'],
  tore: ['torr'],
  torr: ['tore'],
  tori: ['tory'],
  tory: ['tori'],
  tornadoes: ['tornados'],
  tornados: ['tornadoes'],
  torpedoes: ['torpedos'],
  torpedos: ['torpedoes'],
  tort: ['torte'],
  torte: ['tort'],
  totaled: ['totalled'],
  totalled: ['totaled'],
  totaling: ['totalling'],
  totalling: ['totaling'],
  tough: ['tuff'],
  tuff: ['tough'],
  toughed: ['tuft'],
  tuft: ['toughed'],
  tracked: ['tract'],
  tract: ['tracked'],
  tradable: ['tradeable'],
  tradeable: ['tradable'],
  tramel: ['trammel'],
  trammel: ['tramel'],
  transferable: ['transferrable'],
  transferrable: ['transferable'],
  traveled: ['travelled'],
  travelled: ['traveled'],
  traveler: ['traveller'],
  traveller: ['traveler'],
  travelers: ['travellers'],
  travellers: ['travelers'],
  traveling: ['travelling'],
  travelling: ['traveling'],
  tray: ['trey'],
  trey: ['tray'],
  tressel: ['trestle'],
  trestle: ['tressel'],
  troop: ['troupe'],
  troupe: ['troop'],
  troops: ['troupes'],
  troupes: ['troops'],
  trustee: ['trusty'],
  trusty: ['trustee'],
  turbo: ['turbot'],
  turbot: ['turbo'],
  undo: ['undue'],
  undue: ['undo'],
  vail: ['vale', 'veil'],
  vale: ['vail', 'veil'],
  veil: ['vail', 'vale'],
  vain: ['vane', 'vein'],
  vane: ['vain', 'vein'],
  vein: ['vain', 'vane'],
  vales: ['veils'],
  veils: ['vales'],
  vanes: ['veins'],
  veins: ['vanes'],
  vary: ['very'],
  very: ['vary'],
  veers: ['viers'],
  viers: ['veers'],
  vena: ['vina'],
  vina: ['vena'],
  vermilion: ['vermillion'],
  vermillion: ['vermilion'],
  verses: ['versus'],
  versus: ['verses'],
  vice: ['vise'],
  vise: ['vice'],
  vide: ['vied'],
  vied: ['vide'],
  vinal: ['vinyl'],
  vinyl: ['vinal'],
  vita: ['vitae'],
  vitae: ['vita'],
  volcanoes: ['volcanos'],
  volcanos: ['volcanoes'],
  wack: ['whack'],
  whack: ['wack'],
  wacko: ['whacko'],
  whacko: ['wacko'],
  wacks: ['whacks'],
  whacks: ['wacks'],
  waddie: ['waddy'],
  waddy: ['waddie'],
  wade: ['weighed'],
  weighed: ['wade'],
  waggoner: ['wagoner'],
  wagoner: ['waggoner'],
  wail: ['wale', 'whale'],
  wale: ['wail', 'whale'],
  whale: ['wail', 'wale'],
  wailing: ['whaling'],
  whaling: ['wailing'],
  wails: ['wales', 'whales'],
  wales: ['wails', 'whales'],
  whales: ['wails', 'wales'],
  wain: ['wane'],
  wane: ['wain'],
  waist: ['waste'],
  waste: ['waist'],
  waists: ['wastes'],
  wastes: ['waists'],
  wait: ['weight'],
  weight: ['wait'],
  waited: ['weighted'],
  weighted: ['waited'],
  waiting: ['weighting'],
  weighting: ['waiting'],
  waits: ['weights'],
  weights: ['waits'],
  waive: ['wave'],
  wave: ['waive'],
  waived: ['waved'],
  waved: ['waived'],
  waiver: ['waver'],
  waver: ['waiver'],
  waives: ['waves'],
  waves: ['waives'],
  waiving: ['waving'],
  waving: ['waiving'],
  wallie: ['wally'],
  wally: ['wallie'],
  wapping: ['whopping'],
  whopping: ['wapping'],
  ware: ['wear', 'where'],
  wear: ['ware', 'where'],
  where: ['ware', 'wear'],
  wares: ['wears'],
  wears: ['wares'],
  warily: ['wearily'],
  wearily: ['warily'],
  waring: ['wearing'],
  wearing: ['waring'],
  warn: ['worn'],
  worn: ['warn'],
  wary: ['wherry'],
  wherry: ['wary'],
  waterman: ['watermen'],
  watermen: ['waterman'],
  ways: ['weighs'],
  weighs: ['ways'],
  weak: ['week'],
  week: ['weak'],
  weakly: ['weekly'],
  weekly: ['weakly'],
  weary: ['wiry'],
  wiry: ['weary'],
  weather: ['whether'],
  whether: ['weather'],
  weigh: ['whey'],
  whey: ['weigh'],
  weiner: ['whiner', 'wiener'],
  whiner: ['weiner', 'wiener'],
  wiener: ['weiner', 'whiner'],
  welch: ['welsh'],
  welsh: ['welch'],
  wheeled: ['wield'],
  wield: ['wheeled'],
  when: ['wynn'],
  wynn: ['when'],
  which: ['wich', 'witch'],
  wich: ['which', 'witch'],
  witch: ['which', 'wich'],
  whicker: ['wicker'],
  wicker: ['whicker'],
  whigs: ['wigs'],
  wigs: ['whigs'],
  while: ['wile', 'wyle'],
  wile: ['while', 'wyle'],
  wyle: ['while', 'wile'],
  whiles: ['wiles', 'wyles'],
  wiles: ['whiles', 'wyles'],
  wyles: ['whiles', 'wiles'],
  whine: ['wine'],
  wine: ['whine'],
  whines: ['wines'],
  wines: ['whines'],
  whining: ['wining'],
  wining: ['whining'],
  whiny: ['winey'],
  winey: ['whiny'],
  whirl: ['whorl'],
  whorl: ['whirl'],
  whirled: ['world'],
  world: ['whirled'],
  whiskey: ['whisky'],
  whisky: ['whiskey'],
  white: ['wight'],
  wight: ['white'],
  whither: ['wither'],
  wither: ['whither'],
  whys: ['wise'],
  wise: ['whys'],
  wilfully: ['willfully'],
  willfully: ['wilfully'],
  wind: ['wined'],
  wined: ['wind'],
  wins: ['wynns'],
  wynns: ['wins'],
  with: ['withe'],
  withe: ['with'],
  wood: ['would'],
  would: ['wood'],
  woodie: ['woody'],
  woody: ['woodie'],
  woolen: ['woollen'],
  woollen: ['woolen'],
  woolly: ['wooly'],
  wooly: ['woolly'],
  worshipers: ['worshippers'],
  worshippers: ['worshipers'],
  worst: ['wurst'],
  wurst: ['worst'],
  years: ['yours'],
  yours: ['years'],
  yoke: ['yolk'],
  yolk: ['yoke'],
  yokes: ['yolks'],
  yolks: ['yokes'],
  yore: ['your'],
  your: ['yore'],
  zeroes: ['zeros'],
  zeros: ['zeroes'],
}

export function getHomophones(word: string): string[] {
  return HOMOPHONES[word.toLowerCase()] ?? []
}
